### ISSUE TITLE
SEG fault

### ISSUE THREAD

**Issue by MedicineYeh** [KaoCC/StreamingPrototype#49]
``` C++
Starting program: StreamingPrototype/Build/Bin/SP/Debug/x64/SP 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
DeviceInfo: [Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz] [GenuineIntel] [0] [0]
DeviceInfo: [GeForce GTX 780] [NVIDIA Corporation] [1] [0]
Number of APIs: 2
Create APIs
[New Thread 0x7fffea219700 (LWP 6720)]
[New Thread 0x7fffe9a18700 (LWP 6721)]
[New Thread 0x7fffe9217700 (LWP 6722)]
[New Thread 0x7fffe8a16700 (LWP 6723)]
[New Thread 0x7fffe3fff700 (LWP 6724)]
[New Thread 0x7fffe37fe700 (LWP 6725)]
[New Thread 0x7fffe2ffd700 (LWP 6726)]
[New Thread 0x7fffe8215700 (LWP 6727)]
[New Thread 0x7fffe27fc700 (LWP 6728)]
[New Thread 0x7fffe1fe9700 (LWP 6729)]
[New Thread 0x7fffe17d6700 (LWP 6730)]
[New Thread 0x7fffe0fc3700 (LWP 6731)]
[New Thread 0x7fffd8fa8700 (LWP 6732)]
[New Thread 0x7fffc3fff700 (LWP 6733)]
[New Thread 0x7fffc37ec700 (LWP 6734)]
[New Thread 0x7fffc2fd9700 (LWP 6735)]
Create TnI threads
[New Thread 0x7fffc27c6700 (LWP 6738)]
[New Thread 0x7fffc1fc5700 (LWP 6739)]
init data start
init data pass: 
number of shapes: 10
number of lights: 2
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Camera type: Pinhole
Lens focal length: 35mm
Lens focus distance: 1m
F-Stop: inf
Sensor size: 36x36mm
Num of internal Shapes: 10
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Commit
Num of internal Shapes: 10
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Add shape !
Commit
Start Render Thread
>>> number of threads: 9
[New Thread 0x7fff75c4d700 (LWP 6740)]
[New Thread 0x7fff7544c700 (LWP 6741)]
[New Thread 0x7fff74c4b700 (LWP 6742)]
[New Thread 0x7fff67fff700 (LWP 6743)]
[New Thread 0x7fff677fe700 (LWP 6744)]
[New Thread 0x7fff66ffd700 (LWP 6745)]
[New Thread 0x7fff667fc700 (LWP 6746)]
[New Thread 0x7fff65ffb700 (LWP 6747)]
[New Thread 0x7fff657fa700 (LWP 6748)]
Server : Listen on Port 8051
New connection
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[New Thread 0x7fff64ff9700 (LWP 6749)]
[New Thread 0x7fff4ffff700 (LWP 6750)]
[New Thread 0x7fff4f7fe700 (LWP 6751)]
[New Thread 0x7fff4effd700 (LWP 6752)]
[New Thread 0x7fff4e7fc700 (LWP 6753)]
[New Thread 0x7fff4dffb700 (LWP 6754)]
[New Thread 0x7fff4d7fa700 (LWP 6755)]
[New Thread 0x7fff4cff9700 (LWP 6756)]
x264 [info]: profile High 4:4:4 Predictive, level 1.3, 4:4:4 10-bit

Thread 18 "SP" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc27c6700 (LWP 6738)]
0x0000000000446544 in std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<RadeonRays::ray*, RadeonRays::ray*> (
    __first=0x7fffae939000, __last=0x7fffae9f5010, __result=0x204063ff0) at /usr/include/c++/7.1.1/bits/stl_algobase.h:324
324                   *__result = *__first;
(gdb) bt
#0  0x0000000000446544 in std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<RadeonRays::ray*, RadeonRays::ray*> (
    __first=0x7fffae939000, __last=0x7fffae9f5010, __result=0x204063ff0) at /usr/include/c++/7.1.1/bits/stl_algobase.h:324
#1  0x00000000004451fd in std::__copy_move_a<false, RadeonRays::ray*, RadeonRays::ray*> (__first=0x7fffae6f5010, __last=0x7fffae9f5010, 
    __result=0x203e20000) at /usr/include/c++/7.1.1/bits/stl_algobase.h:386
#2  0x00000000004439ba in std::__copy_move_a2<false, __gnu_cxx::__normal_iterator<RadeonRays::ray*, std::vector<RadeonRays::ray, std::allocator<RadeonRays::ray> > >, RadeonRays::ray*> (__first=
    {o = {x = -0.566153586, y = 0.146519884, z = -0.0231212322, w = 3.40282347e+38}, d = {x = 0.44013384, y = 0.897757888, z = -0.0176923964, w = 0}, extra = {x = -1, y = 1}, padding = {x = 0, y = 0}}, __last=
    {o = {x = 0, y = 0, z = 0, w = 0}, d = {x = 0, y = 0, z = 0, w = 0}, extra = {x = 0, y = 0}, padding = {x = 0, y = 0}}, __result=0x203e20000)
    at /usr/include/c++/7.1.1/bits/stl_algobase.h:424
#3  0x0000000000441dbc in std::copy<__gnu_cxx::__normal_iterator<RadeonRays::ray*, std::vector<RadeonRays::ray, std::allocator<RadeonRays::ray> > >, RadeonRays::ray*> (__first=
    {o = {x = -0.566153586, y = 0.146519884, z = -0.0231212322, w = 3.40282347e+38}, d = {x = 0.44013384, y = 0.897757888, z = -0.0176923964, w = 0}, extra = {x = -1, y = 1}, padding = {x = 0, y = 0}}, __last=
    {o = {x = 0, y = 0, z = 0, w = 0}, d = {x = 0, y = 0, z = 0, w = 0}, extra = {x = 0, y = 0}, padding = {x = 0, y = 0}}, __result=0x203e20000)
    at /usr/include/c++/7.1.1/bits/stl_algobase.h:456
#4  0x000000000043f428 in SP::ApiEngine::occlude (api=0x11fd340, buffer=..., data=...) at ../SP/src/Renderer/ApiEngine.cpp:201
#5  0x000000000044bb85 in std::__invoke_impl<void, void (*&)(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData), RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData&> (__f=
    @0x7fff60000978: 0x43f34c <SP::ApiEngine::occlude(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData)>, 
    __args#0=@0x7fffc27c5ca0: 0x11fd340, __args#1=..., __args#2=...) at /usr/include/c++/7.1.1/bits/invoke.h:60
#6  0x000000000044b82b in std::__invoke<void (*&)(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData), RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData&> (__fn=
    @0x7fff60000978: 0x43f34c <SP::ApiEngine::occlude(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData)>, 
    __args#0=@0x7fffc27c5ca0: 0x11fd340, __args#1=..., __args#2=...) at /usr/include/c++/7.1.1/bits/invoke.h:95
#7  0x000000000044b40a in std::_Bind<void (*(std::_Placeholder<1>, std::_Placeholder<2>, SP::ApiEngine::OccludeData))(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData)>::__call<void, RadeonRays::IntersectionApi*&&, SP::ApiEngine::BackendBuffer&&, 0ul, 1ul, 2ul>(std::tuple<RadeonRays::IntersectionApi*&&, SP::ApiEngine::BackendBuffer&&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x7fff60000978, 
    __args=...) at /usr/include/c++/7.1.1/functional:467
#8  0x000000000044aabc in std::_Bind<void (*(std::_Placeholder<1>, std::_Placeholder<2>, SP::ApiEngine::OccludeData))(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData)>::operator()<RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, void>(RadeonRays::IntersectionApi*&&, SP::ApiEngine::BackendBuffer&&) (this=0x7fff60000978, __args#0=@0x7fffc27c5ca0: 0x11fd340, __args#1=...)
    at /usr/include/c++/7.1.1/functional:551
#9  0x000000000044a406 in std::__invoke_impl<void, std::_Bind<void (*(std::_Placeholder<1>, std::_Placeholder<2>, SP::ApiEngine::OccludeData))(RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer, SP::ApiEngine::OccludeData)>&, RadeonRays::IntersectionApi*, SP::ApiEngine::BackendBuffer>(std::__invoke_other, std::_Bind<void (*(std::_Placeholder<1>, std::_Placeholder<2>, SP::ApiEngine::OccludeData))(RadeonRays::IntersectionApi*, SP::---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) up 4
#4  0x000000000043f428 in SP::ApiEngine::occlude (api=0x11fd340, buffer=..., data=...) at ../SP/src/Renderer/ApiEngine.cpp:201
201                     std::copy(data.shadowrayBuffer.begin(), data.shadowrayBuffer.end(), rawShadowrayPtr);
(gdb) 
```

**Comment by KaoCC** [comment]
Note: [GeForce GTX 780] [NVIDIA Corporation]

**Comment by KaoCC** [comment]
fixed
